[[source]]
name = "爱看漫"
version = "1.0.0"
fileName = "ikmmh.toml"
description = "网站: https://ymcdnyfqdapp.ikmmh.com/"

[[source]]
name = "拷贝漫画"
version = "1.0.2"
fileName = "copy_manga.toml"
description = "网站: https://www.copymanga.site/"
